---
title: "Visuales esotéricos audioreactivos con shaders y GLSL"
output: html_document
---
**Instructor: Synthesaurio (a.k.a Pablo Gomez)**


## Descripción del taller

En este taller exploraremos la intersección entre audio y visuales mediante el uso de GLSL dentro del software multiplataforma (windows, mac, ios, android y linux) [Kodelife](https://hexler.net/kodelife). GLSL es un lenguaje de programación para gráficos computacionales llamados shaders. Múltiples plataformas de libre acceso proveen soporte a este lenguaje (i.e. touchdesigner, Meta spark AR, Unity). Algunas de estas plataformas permiten intervenir los shaders con señales externas como audio o midi, proporcionando la oportunidad de producir visuales generativos en tiempo real que responden a música o sonido. 
El taller está planteado desde una perspectiva multidisciplinaria en la que se integran conocimientos básicos de áreas como música, gráficos computacionales y programación. No es necesario que los participantes tengan experiencia en estas áreas, ya que el principal enfoque es que exploren el material desde su propia perspectiva y percepción de la realidad, utilizando las herramientas proporcionadas con un enfoque artístico y creativo, e interactuando con los demás participantes e instructor.

No es necesario contar con conocimientos previos en programación, se recomienda a los participantes traer sus propios medios digitales a intervenir (videos, imágenes, audios). 

## Objetivos del taller

- Familiarizarse con el lenguaje de programación GLSL
- Entender como integrar señales externas como audio en los visuales
- Como integrar el uso de GLSL a otro software (p. ej. touchdesigner)

## Herramientas a usar 

- Hardware: Computadora personal. De preferencia windows o mac
- Software: [Kodelife](https://hexler.net/kodelife)
- *Opcional: touchdesigner*

## Contenido del taller

El taller consiste en una combinación de presentaciones interactivas y ejercicios diseñados para familiarizarse con el lenguaje de programación GLSL y las herramientas disponibles para su implementación. 
Durante las presentaciones, los participantes tendrán oportunidad de interactuar con el instructor y revisar conceptos básicos en audio y gráficos computacionales, y en los ejercicios implementaran estos conceptos para generar e intervenir piezas audiovisuales. 
No es necesario contar con conocimientos previos en programación, se recomienda a los participantes traer sus propios medios digitales a intervenir (videos, imágenes, audios) para mejorar la interacción y los resultados obtenidos al final del taller.


| Dia | Tema                          |
|---------|:--------------------------|
| 01  | [Coordenadas, color y dinamica](https://ucdavis.box.com/s/buhe6vg36gxsvzb4g7ztadtcs18hrtrm) |
| 02  | [Texturas, buffers y feedback](https://ucdavis.box.com/s/zmprubcakme1xqku3tzogd9vjzovm6at)  |
| 03  | [Mas alla de los basicos](https://ucdavis.box.com/s/enwvc78kemrqgsjs2ax3hfqmxm0zcj3u)       |


## Enlaces de referencia

  - [Funciones para formas](https://iquilezles.org/articles/distfunctions2d/)
  - [Stickersheet de Char stiles](https://gist.github.com/CharStiles/e6fec016967c6c8fd648aa4b6c0055cc)
  - [The book of shaders:](https://thebookofshaders.com) La biblia de referencia para shaders
  - [Hypno videopacks](https://sleepycircuits.com/latest-video-pack), libreria de videos gratis
  - [Blend modes](https://www.shadertoy.com/view/4tSGWV)
  - [Como hacer Datamosh?](https://interactiveimmersive.io/blog/glsl/datamoshing-in-touchdesigner-part-3/)
  - Cosas de 3D:
    - [Sketchfab](https://sketchfab.com/) libreria de geometrias 3D
    - [Blender](https://www.blender.org/download/) Software de edicion para modelos 3D
    - [Meta Spark toolkit](https://spark.meta.com/learn/articles/creating-and-prepping-assets/toolkit-for-blender) addin de blender para simplificar geometrias
  - [Otras funciones](https://github.com/synthesaurio/visuales-esotericos/blob/main/checkpoints/funciones.glsl)
  
  
-------------------


## Posicionalidad del expositor:

Pablo Gomez, nacido en Guanajuato Mexico; Investigador en el Centro de Modelación de Enfermedades Animales (CADMS) de la universidad de California de día y artista audiovisual de noche. A través de mi trayectoria he sido afortunado de ver el mundo desde diferentes perspectivas; desde trabajando en granjas remotas en la frontera sur de Mexico, hasta trabajando en el sótano de una institución de investigación rodeado de computadoras. Estoy interesado en la intersección de la ciencia y el arte, y las aplicaciones de la tecnología para descifrar la belleza en sistemas complejos. En mi trabajo de día utilizo métodos en programación y matemáticas, tales como modelos de simulación y estadística espacio-temporal; en mi practica artística me gusta explorar técnicas de composición algorítmica para generar visuales y musica. Encuentro mi inspiración en la interralación de las sociedades humanas con la naturaleza, y me gusta pensar que mi trabajo sirve como enlace entre diferentes areas de conocimiento.
En mi trayectoria profesional he impartido diferentes cursos con participantes de más de 20 países en diferentes sectores como academia, gobierno o industria privada. 

instagram: http://instagram.com/synthesaurio.av/. 

website: https://www.synthesaurio.com   

Reel de trabajo: https://youtu.be/xI9KrOo1SmY. 
